.TH laptop-keyboard 1 "6 Abr 2025" "version 0.1"

.SH NAME
laptop-keyboard - activa o desactiva el teclado de la laptop (X11)

.SH SINOPSYS
.B laptop-keyboard
[on|off]

.SH DESCRIPTION
Controla cuando el teclado de la laptop está conectado o no a su
dispositivo maestro

.SH AUTHOR
Diacus Magnuz
.I <diacus.magnuz@gmail.com>
